apiVersion: v1
kind: Pod
metadata:
  name: employee-k8s
  labels:
    name: employee-k8s
spec:
  containers:
  - name: employee-k8s
    image: jimmyshah83/pws-spring-boot-demo:docker-spring-boot-tag
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"