resources:
- name: git-repo
  type: git
  source:
    branch: master
    uri: https://github.com/jimmy-pivotal/pws-spring-boot-demo.git

jobs:
- name: Unit Tests
  public: false
  plan:
    - get: git-repo
      trigger: true
    - task: Run Unit Tests
      file: git-repo/ci/task_run_tests.yml