resources:
- name: git-repo
  type: git
  source:
    branch: master
    uri: https://github.com/jimmy-pivotal/pws-spring-boot-demo.git

- name: deploy-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((USER_CF))
    password: ((PASSWORD_CF))
    organization: Canada
    space: jishah
    skip_cert_check: false

jobs:
- name: Unit Tests
  public: true
  plan:
    - get: git-repo
      trigger: true
    - task: Run Unit Tests
      file: git-repo/ci/task_run_tests.yml

- name: Build Project
  public: true
  plan:
    - get: git-repo
      passed: [Unit Tests]
      trigger: true
    - task: Build Code
      file: git-repo/ci/task_buildcode.yml
    - put: deploy-cf
      params:
        manifest: git-repo/manifest.yml
        path: artifacts/*.jar